[package]
name = "simple-token-creator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
solana-sdk = "2.1"
solana-client = "2.1"
spl-associated-token-account = "7.0"
spl-token = "8.0"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
dotenvy = "0.15"
